import uuid
from datetime import datetime, timezone
from sqlalchemy import Column, String, Text, DateTime, Float, JSON
from sqlalchemy.dialects.postgresql import UUID
from geoalchemy2 import Geometry
from app.core.database import Base


class CitizenRequest(Base):
    """
    SQLAlchemy Model for storing incoming multi-channel citizen requests.
    Supports PostGIS spatial indexing for fast geospatial clustering and heatmaps.
    """
    __tablename__ = "citizen_requests"

    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        index=True,
        comment="Unique identifier for the citizen request event",
    )
    timestamp = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
        index=True,
        comment="UTC timestamp when the signal was received",
    )
    channel = Column(
        String(50),
        nullable=False,
        default="unknown",
        index=True,
        comment="Ingestion channel: whatsapp, telegram, twilio_voice, sms, web",
    )
    original_language = Column(
        String(20),
        nullable=False,
        default="unknown",
        index=True,
        comment="Detected or specified source language code (e.g. hi, pt, ru, zh, ar)",
    )
    original_text = Column(
        Text,
        nullable=True,
        comment="PII-sanitized transcript or text in the original language",
    )
    english_translation = Column(
        Text,
        nullable=False,
        comment="Unified English translation generated by the LLM baseline",
    )
    category = Column(
        String(100),
        nullable=False,
        default="unclassified",
        index=True,
        comment="Categorized public good domain (e.g., Healthcare, Water, Power, Infrastructure)",
    )
    latitude = Column(
        Float,
        nullable=True,
        comment="WGS84 Latitude",
    )
    longitude = Column(
        Float,
        nullable=True,
        comment="WGS84 Longitude",
    )
    # PostGIS Point Geometry: SRID 4326 (WGS 84 GPS coordinates: Longitude, Latitude)
    location = Column(
        Geometry(geometry_type="POINT", srid=4326),
        nullable=True,
        index=True,
        comment="PostGIS Geometry Point (Longitude, Latitude) for spatial querying",
    )
    raw_metadata = Column(
        JSON,
        nullable=True,
        default=dict,
        comment="Extensible sanitized metadata such as sender channel ID, carrier, or audio metrics",
    )

    def __repr__(self) -> str:
        return (
            f"<CitizenRequest(id={self.id}, channel={self.channel}, "
            f"lang={self.original_language}, category={self.category})>"
        )
