import uuid
from datetime import datetime, timezone
from sqlalchemy import Column, String, Text, DateTime, Float, JSON, Integer
from app.core.database import Base


class CitizenRequest(Base):
    """
    SQLAlchemy Model for storing incoming multi-channel citizen requests.
    Supports persistent local SQLite DBMS and PostgreSQL.
    Tracks urgency, AI classification, deduplication counts, and spatial coordinates.
    """
    __tablename__ = "citizen_requests"

    id = Column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
        index=True,
        comment="Unique identifier for the citizen request event",
    )
    timestamp = Column(
        DateTime,
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
        index=True,
        comment="UTC timestamp when the signal was received",
    )
    channel = Column(
        String(50),
        nullable=False,
        default="web",
        index=True,
        comment="Ingestion channel: web, voice, whatsapp, telegram, sms",
    )
    original_language = Column(
        String(20),
        nullable=False,
        default="en",
        index=True,
        comment="Detected or specified source language code (e.g. hi, pt, ru, zh, ar, en)",
    )
    original_text = Column(
        Text,
        nullable=True,
        comment="PII-sanitized transcript or text in the original language",
    )
    english_translation = Column(
        Text,
        nullable=False,
        comment="Unified English translation generated by the AI / transformer baseline",
    )
    category = Column(
        String(100),
        nullable=False,
        default="unclassified",
        index=True,
        comment="Categorized public good domain (e.g., Water & Sanitation, Healthcare, Grid & Power, Transport & Logistics)",
    )
    urgency = Column(
        String(20),
        nullable=False,
        default="MEDIUM",
        index=True,
        comment="Urgency classification: CRITICAL, HIGH, MEDIUM, LOW",
    )
    urgency_score = Column(
        Float,
        nullable=False,
        default=50.0,
        comment="Calculated urgency index (0.0 to 100.0)",
    )
    duplicate_count = Column(
        Integer,
        nullable=False,
        default=1,
        comment="Number of similar citizen complaints grouped into this signal",
    )
    cluster_id = Column(
        String(100),
        nullable=True,
        index=True,
        comment="Geospatial hotspot / cluster identifier",
    )
    latitude = Column(
        Float,
        nullable=True,
        comment="WGS84 Latitude",
    )
    longitude = Column(
        Float,
        nullable=True,
        comment="WGS84 Longitude",
    )
    country = Column(
        String(100),
        nullable=True,
        default="BRICS Global",
        comment="BRICS member country",
    )
    region = Column(
        String(100),
        nullable=True,
        comment="Metropolitan or regional administrative district",
    )
    raw_metadata = Column(
        JSON,
        nullable=True,
        default=dict,
        comment="Sanitized metadata including audio duration, sentiment, extracted entities",
    )

    def __repr__(self) -> str:
        return (
            f"<CitizenRequest(id={self.id}, channel={self.channel}, "
            f"lang={self.original_language}, cat={self.category}, urgency={self.urgency}, dups={self.duplicate_count})>"
        )
